defaults:
- dataset: train_denoise #train_grb_local_all #demo_all #train_grb_all #train_grb #train_grb_all #demo #dataset_gray #main #server_train_rgb
- model: NAFNet #NAFNet #DRUnet #SwinIRLight #DRUnet #NAFNet
- optimizer: adam  #adam
#- hydra/sweeper: optuna #Optuna hyperparamater optimization program

train_config:
  scale: 1
  colors: 3
  mode: 'denoise'
  seed:       101
  debug:      False #set debug=False for Full Training
  description: "denoise"
  comment:    ${model.name}_ep_${train_config.epochs}_op_${optimizer.name}_lr_${optimizer.lr}_size_${train_config.patch_size}_loss_${losses.name}_des_${train_config.description}
  device:     "cuda"
  img_save_val: True
  pixel_recovery: True
  save_img_rec: True
  warm_up: True
  db_split: False

  ## parameters for model training
  patch_size: 256 #128
  batch_size: 4 #16
  batch_size_val: 2
  data_repeat: 1
  data_augment: 1
  start_epoch: 0
  epochs: 200
  log_every: 100
  test_every: 3
  log_path: "./experiments"
  store_in_ram: 0
  nclass: 2
  ignore_index: 250
  #pretrain: '/workspace/09_CHALLENGE/ECCV/ECBSR/chekpoint/model_x3_75.pt'
  testmodelpath:  '/workspace/11_IMAGE_DENOISE/pixel_error_recovery/checkpoint/previous_work/NAFNet_best_epoch.pt'
  pretrain: #'/workspace/11_IMAGE_DENOISE/pixel_error_recovery/checkpoint/last_epoch_hybrid_ml1.pt'
  resume: 
  mixed_pred: True
  ## hardware specification
  gpu_id: 0
  num_workers: 8
  threads: 1
  wandb: 0
  fsize: 2
  use_masked_loss: False
  early_stop: 100
losses:
  name:         'l1'