defaults:
- dataset: train_grb_all #demo_all #train_grb_all #train_grb #train_grb_all #demo #dataset_gray #main #server_train_rgb
- model: plain_hybrid_pixel #UNetWithResnet50Hybrid #UNetWithResnet50Hybrid #UNetWithResnet50Encoder #ecbsr #fsrcnn
- optimizer: adam  #adam
#- hydra/sweeper: optuna #Optuna hyperparamater optimization program

train_config:
  scale: 1
  colors: 3
  mode: 'hybrid'
  seed:       101
  debug:      False #set debug=False for Full Training
  description: "local_hybrid"
  comment:    ${model.name}_ep_${train_config.epochs}_op_${optimizer.name}_lr_${optimizer.lr}_size_${train_config.patch_size}_loss_${losses.name}_des_${train_config.description}
  device:     "cuda"
  img_save_val: True
  pixel_recovery: True
  save_img_rec: True
  warm_up: True
  db_split: False

  ## parameters for model training
  patch_size: 256
  batch_size: 32
  batch_size_val: 10
  data_repeat: 2
  data_augment: 1
  start_epoch: 0
  epochs: 400
  log_every: 100
  test_every: 5
  log_path: "./experiments"
  lr: 0.0005
  store_in_ram: 0
  nclass: 2
  ignore_index: 250
  #pretrain: '/workspace/09_CHALLENGE/ECCV/ECBSR/chekpoint/model_x3_75.pt'
  testmodelpath:  '/workspace/11_IMAGE_DENOISE/pixel_error_recovery/checkpoint/last_epoch_hybrid_ml1.pt'
  pretrain: #'/workspace/11_IMAGE_DENOISE/pixel_error_recovery/checkpoint/last_epoch_hybrid_ml1.pt'
  resume: 
  mixed_pred: False
  ## hardware specification
  gpu_id: 1
  threads: 1
  wandb: 1
  fsize: 2
  use_masked_loss: True
losses:
  name:         'bootstrapped_cross_entropy2d_hybrid_l2'